project:
  type: book

book:
  title: "Avaliação do Risco de Extinção de Espécies"
  author: "Lucas S.B. Jordão"
  date: "23/03/2025"
  chapters:
    - index.qmd
    - iucn.qmd
    - lista-vermelha.qmd
    - qualidade-dos-dados.qmd
    - categorias.qmd
    - criterios.qmd
    - avaliacao.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: litera
      dark: morph
    number-sections: false
    crossref:
      fig-prefix: "Figura"
    css: "style.css"
    include-in-header:
      - text: |
          <script src="nav-arrows.js"></script>

lang: pt

comments:
  hypothesis: 
    theme: clean
  giscus: 
    repo: lsbjordao/Avaliacao-risco-extincao-IUCN
