# Lista Vermelha

## Relevância

Qual é a probabilidade de uma espécie se
tornar extinta num futuro próximo,
considerando o conhecimento atual sobre
tendências populacionais, distribuição
geográfica e ameaças recentes, atuais ou
projetadas?

Avaliação da Lista Vermelha da
IUCN é uma estimativa do risco de
extinção

Não apenas uma lista, mas uma compilação dos status de conservação das espécies em nível global 

Com base nas melhores informações científicas disponíveis

Amplamente utilizado para informar e influenciar a conservação da biodiversidade.

• Mais do que apenas nomes e
categorias de ameaças
• Inclui informações sobre ameaças
(por exemplo, espécies invasoras),
requisitos ecológicos e ações de
conservação
• As avaliações das espécies são
geradas por meio do conhecimento
de milhares dos principais cientistas
do mundo, por meio de um processo
de revisão.

## Objetivos

### Objetivo Geral

Fonte de informação mais abrangente do mundo sobre o risco de extinção das espécies.

Fornecer informações e análises sobre o status, tendências e ameaças às espécies, a fim de informar e catalisar ações para a conservação da biodiversidade.

### Objetivos específicos

Estabelecer uma linha de base a partir da qual
monitora a mudança nos status das espécies.
• Fornecer um contexto global para estabelecer
prioridades de conservação em nível local.
• Monitorar de forma contínua o status de uma
seleção representativa de espécies (como
indicadores de biodiversidade) que abrangem
todos os principais ecossistemas do mundo.
